color = input("Enter colors(space between colors): ") 
color_list = color.split(" ") 
print(color_list) 
print("First color in the list is ", color_list[0]) 
print("Last color in the list is ", color_list[-1]) 
